# Generated by Django 4.0.1 on 2022-01-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedassets',
            name='name',
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='accounting_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='accumulated_depreciation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='book_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='commissioning_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='depreciation_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='initial_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='inventory_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='main_face',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='percent_annual_depr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='period_of_execution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='property_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fixedassets',
            name='upgrade_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
