# Generated by Django 4.0.1 on 2022-01-26 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_fixedassets_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(blank=True, max_length=128, null=True)),
                ('asset_selection', models.CharField(blank=True, max_length=128, null=True)),
                ('order_date', models.IntegerField(blank=True, null=True)),
                ('storage', models.CharField(blank=True, max_length=128, null=True)),
                ('choose_assets', models.CharField(blank=True, max_length=128, null=True)),
                ('inventory_number', models.IntegerField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=128, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=128, null=True)),
                ('initial_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('method_of_entry', models.CharField(blank=True, max_length=128, null=True)),
                ('current_state', models.CharField(blank=True, max_length=128, null=True)),
                ('accounting_account', models.IntegerField(blank=True, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=30, null=True)),
                ('factory_number', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('present_value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.RenameField(
            model_name='fixedassets',
            old_name='data',
            new_name='date_time',
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depreciation_account', models.IntegerField(blank=True, null=True)),
                ('depreciation_method', models.CharField(blank=True, max_length=30, null=True)),
                ('preliminary_work', models.IntegerField(blank=True, null=True)),
                ('depreciation_schedule', models.IntegerField(blank=True, null=True)),
                ('period_of_execution', models.IntegerField(blank=True, null=True)),
                ('current_depreciation', models.IntegerField(blank=True, null=True)),
                ('depreciation_per_year', models.IntegerField(blank=True, null=True)),
                ('percent_annual_depr', models.IntegerField(blank=True, null=True)),
                ('assets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation', to='assets.assets')),
            ],
            options={
                'db_table': 'depreciation',
            },
        ),
        migrations.CreateModel(
            name='CommissionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_members', to='assets.assets')),
            ],
            options={
                'db_table': 'commission_member',
            },
        ),
    ]
