# Generated by Django 4.0.1 on 2022-01-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assets_rename_data_fixedassets_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='order',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
