# Generated by Django 4.0.1 on 2022-01-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assets_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionmember',
            options={'verbose_name': 'Члены комиссии'},
        ),
        migrations.AlterModelOptions(
            name='depreciation',
            options={'verbose_name': 'Амортизация'},
        ),
        migrations.AlterModelOptions(
            name='fixedassets',
            options={'verbose_name': 'Принятие на счет ОС'},
        ),
    ]
