# Generated by Django 4.0.1 on 2022-01-28 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_commissionmember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={'verbose_name': 'Средства'},
        ),
    ]
