# Generated by Django 4.0.1 on 2022-01-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_assets_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={'verbose_name': 'Средства', 'verbose_name_plural': 'Средства'},
        ),
        migrations.AlterModelOptions(
            name='commissionmember',
            options={'verbose_name': 'Члены комиссии', 'verbose_name_plural': 'Члены комиссии'},
        ),
        migrations.AlterModelOptions(
            name='depreciation',
            options={'verbose_name': 'Амортизация', 'verbose_name_plural': 'Амортизации'},
        ),
        migrations.AlterModelOptions(
            name='fixedassets',
            options={'verbose_name': 'Принятие на счет ОС', 'verbose_name_plural': 'Принятия на счет ОС'},
        ),
    ]
