# Generated by Django 4.0.1 on 2022-01-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_assets_options_alter_commissionmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='current_state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
